code-wars/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'
  
  resources :users
  # resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  

  
  resources :battles
  resources :character_battles
  resources :characters
  resources :factions



end

code-wars/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

code-wars/app/models/battle.rb
class Battle < ApplicationRecord
    has_many :character_battles
    has_many :characters, through: :character_battles

    def battle_choice
        user_num = rand(11)
        char_num = rand(11)
        if user_num > char_num
            1
        elsif char_num > user_num
            2
        elsif char_num == user_num
            3
        end
    end


end

code-wars/app/models/character.rb
class Character < ApplicationRecord
    belongs_to :faction
    belongs_to :user
    has_many :character_battles
    has_many :battles, through: :character_battles

    validates :name, presence: true, uniqueness: true
    validates :description, presence: {message: " and/or background can't be blank"}


    def character_loss
        new_battles_lost = self.battles_lost + 1
        self.update(battles_lost: new_battles_lost)
    end

    def character_win
        new_battles_won = self.battles_won + 1
        self.update(battles_won: new_battles_won)
    end

    
end

code-wars/app/models/character_battle.rb
class CharacterBattle < ApplicationRecord
    belongs_to :character
    belongs_to :battle
end

code-wars/app/models/faction.rb
class Faction < ApplicationRecord
    has_many :characters
end

code-wars/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :characters

  validates :email, presence: true, uniqueness: true, length: {minimum: 5}
  validates :password_digest, length: {minimum: 5}

  def user_characters
    
    Character.all.select do | character | 
        self.id == character.user_id
    end
  end

  def user_loss
    new_battles_lost = self.battles_lost + 1
    self.update(battles_lost: new_battles_lost)
  end

  def user_win
    new_battles_won = self.battles_won + 1
    self.update(battles_won: new_battles_won)
  end
end

code-wars/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end
end

code-wars/app/controllers/battles_controller.rb
class BattlesController < ApplicationController

    def index
        @battles = Battle.all
    end

    def show 
        @battle = Battle.find(params[:id])
        
        Character.all.each do | character | 
            if @battle.winner_id == character.id 
                @winner = character 
            end 
        end 
        
        Character.all.each do | character | 
            if @battle.loser_id == character.id 
                @loser = character 
            end 
        end 
    end
    

end

code-wars/app/controllers/characters_controller.rb
class CharactersController < ApplicationController

    def index
        @characters = Character.all
    end

    def show 
        @character = Character.find(params[:id])
    end
    
    def new
        @character = Character.new
    end
    
    def create
        @character = Character.create(character_params)

        if @character.valid?
            @character.save
            redirect_to character_path(@character)
        else
            flash[:errors] = @character.errors.full_messages
            redirect_to new_character_path
        end
    end

    def destroy
        @character = Character.find_by(id: params[:id])
        @character.destroy
        redirect_to characters_path
    end

    private

    def character_params
        params.require(:character).permit(:name, :species, :description, :faction_id, :classification, :status, :battles_won, :battles_lost, :user_id)
    end
        
    # t.string :name
    # t.string :species
    # t.string :description
    # t.string :faction_id
    # t.string :classification
end

code-wars/app/controllers/factions_controller.rb
class FactionsController < ApplicationController


    def index
        @factions = Faction.all
    end

    def show 
        @faction = Faction.find(params[:id])
    end
    


end

code-wars/app/controllers/fights_controller.rb
class FightsController < ApplicationController

    attr_writer :rand_seed

    def initialize(guess:)
        @guess = guess.downcase
    end

    def random_choice
        rand 500
    end

    def computer_choice
        srand (@rand_seed || random_choice)
        computer_choices = %w{rock paper scissors}
        computer_choices.sample
    end

    def winner_is
        if rule_engine[computer_choice.to_sym].include? @guess
            'Enemy Wins'
        elsif rule_engine[@guess.to_sym].include? computer_choice
            'You Win'
        else
            'Tie'
        end
    end

    def rule_engine
        {
            'rock': ['scissors'],
            'paper': ['rock'],
            'scissors': ['paper'],
        }
    end
end

code-wars/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

code-wars/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    session.clear
    redirect_to root_url, notice: "Logged out!"
  end

end

code-wars/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:id] = @user.id
        format.html { redirect_to root_url, notice: 'Account was successfully created. Please log in.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

code-wars/app/helpers/application_helper.rb
module ApplicationHelper
end

code-wars/app/helpers/battles_helper.rb
module BattlesHelper
end

code-wars/app/helpers/character_battles_helper.rb
module CharacterBattlesHelper
end

code-wars/app/helpers/characters_helper.rb
module CharactersHelper
end

code-wars/app/helpers/factions_helper.rb
module FactionsHelper
end

code-wars/app/helpers/home_helper.rb
module HomeHelper
end

code-wars/app/helpers/sessions_helper.rb
module SessionsHelper
end

code-wars/app/helpers/users_helper.rb
module UsersHelper
end

code-wars/app/views/factions/index.html.erb
<div class="navbar">
    <a href="http://localhost:3000/"><img src="http://arcos-platform.site/wp-content/uploads/2021/01/PosterArtboard-1-copyAsset.png" width="225" height="25"</a>
    <a href="http://localhost:3000/characters">Characters</a>
    <a href="http://localhost:3000/factions">Factions</a>
        <div class="topnav-right">
            
            
            <% if current_user %>
            <%= link_to "Your Crew", user_path(session[:user_id])%>
            <%= link_to "Log Out", logout_path %>
            <% else %>
            <%= link_to "Sign Up", signup_path %> 
            <%= link_to "Log In", login_path %>
            <% end %>
        </div>
</div>
<br>
<br>
<br>
<h1> Factions </h1>
    <br>
    <ul>
    <% @factions.each do |faction| %>
        <li> <h3> <%= link_to faction.name, faction_path(faction) %><br> </h3>
    <% end %>
    </ul> <br>

code-wars/app/views/factions/show.html.erb
<div class="navbar">
    <a href="http://localhost:3000/"><img src="http://arcos-platform.site/wp-content/uploads/2021/01/PosterArtboard-1-copyAsset.png" width="225" height="25"</a>
    <a href="http://localhost:3000/characters">Characters</a>
    <a href="http://localhost:3000/factions">Factions</a>
        <div class="topnav-right">
            
            
            <% if current_user %>
            <%= link_to "Your Crew", user_path(session[:user_id])%>
            <%= link_to "Log Out", logout_path %>
            <% else %>
            <%= link_to "Sign Up", signup_path %> 
            <%= link_to "Log In", login_path %>
            <% end %>
        </div>
</div>
<br>
<br>
<br>
<h1> Selected Factions </h1>

<h3> Name: <%=@faction.name%> </h3>
<h3> Description: <%=@faction.description%> </h3>
<h3> Notable Characters: </h3>

<ul>
    <% @faction.characters.each do | character | %>
        <li> <h3> <%= link_to character.name, character_path(character.id) %> <br> </h3>
    <% end %>
</ul> <br>

code-wars/app/views/home/index.html.erb
<div class="navbar">
    <a href="http://localhost:3000/"><img src="http://arcos-platform.site/wp-content/uploads/2021/01/PosterArtboard-1-copyAsset.png" width="225" height="25"</a>
    <a href="http://localhost:3000/characters">Characters</a>
    <a href="http://localhost:3000/factions">Factions</a>
        <div class="topnav-right">
            
            
            <% if current_user %>
            <%= link_to "Your Crew", user_path(session[:user_id])%>
            <%= link_to "Log Out", logout_path %>
            <% else %>
            <%= link_to "Sign Up", signup_path %> 
            <%= link_to "Log In", login_path %>
            <% end %>
        </div>
</div>

<% if !session[:user_id] %>
<div class="precontainer">
    
    <div class="banner">
        <div class="app-text">
            <h1>War! </h1>
            <p>
            The republic crumbles<br>
            Its a dark time for the rebellion<br>
            The death star has been destroyed<br>
            The fate of the galaxy falls on you...
            <br> <br>
            Log In to enter the Fray!
            </p>
        </div>
   
    </div>
</div>
<% end %>


<% if session[:user_id] %>
<div class="container">
    
    <div class="banner">
        <div class="app-text">
            <h1>War! </h1>
            <p>
            The republic crumbles<br>
            Its a dark time for the rebellion<br>
            The death star has been destroyed<br>
            The fate of the galaxy falls on you...
            </p>
        </div>
   
    </div>
</div>


<div class="home-body">
    <div class="banner2">
        <div class="app-text">
            <h1>Code Wars</h1>
            <p>
            Welcome to the Star Wars Battle tracker<br>
            Create a basic Star Wars character of your own and<br>
            pit them against other user characters and galatic <br>
            legends throughout the entire Star Wars series!
            </p>
            <a href="http://localhost:3000/characters/new"><div class="gradient-button gradient-button-4">Character Creator
            </div></a>
    
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
</div>


<div class="home-body2">
    <div class="banner3">
        <div class="app-text">
        <h1>Choose a Side</h1>
        <p>
        With the galaxy at war you must choose,<br>
        order and power or justice and peace
        </p>
        <a href="http://localhost:3000/factions"><div class="gradient-button gradient-button-1">Explore Factions
            </div></a>
        
        </div>
    
    </div>
    <br>
    <br>
    <br>
    <br>

</div>


<div class="home-body3">
    <div class="banner4">
        <div class="app-text2">
        <h1>Meet the Heroes</h1>
        <p>
        Play with—and against—Star Wars most feared<br>
        villains and cherished heroes from any era<br>
        including Kylo Ren, Rey, Darth Maul, Yoda, and many more.
        </p>
        <a href="http://localhost:3000/characters"><div class="gradient-button gradient-button-1">Heroes
            </div></a>
        
        </div>
    
    </div>
    <br>
    <br>
    <br>
    <br>

</div>
<div class="home-body4">
    <div class="banner5">
        <div class="app-text2">
        <h1>Duel of Fates</h1>
        <p>
        If your ready and logged in step into the ring!
        </p>
        <%= link_to 'Battle', new_character_battle_path(:id => session[:user_id]), class: "gradient-button gradient-button-2", style: "text-decoration: none" %>

    </div>
    <br>
    <br>
    <br>
    <br>
</div>
<% end %>