code-wars/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'
  
  resources :users
  # resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  

  
  resources :battles
  resources :character_battles
  resources :characters
  resources :factions



end

code-wars/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :characters

  validates :email, presence: true, uniqueness: true, length: {minimum: 5}
  validates :password_digest, length: {minimum: 5}

  def user_characters
    
    Character.all.select do | character | 
        self.id == character.user_id
    end
  end

  def user_loss
    new_battles_lost = self.battles_lost + 1
    self.update(battles_lost: new_battles_lost)
  end

  def user_win
    new_battles_won = self.battles_won + 1
    self.update(battles_won: new_battles_won)
  end
end

code-wars/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:id] = @user.id
        format.html { redirect_to root_url, notice: 'Account was successfully created. Please log in.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

code-wars/app/helpers/users_helper.rb
module UsersHelper
end

code-wars/app/views/users/_form.html.erb
<div class="navbar">
    <a href="http://localhost:3000/"><img src="http://arcos-platform.site/wp-content/uploads/2021/01/PosterArtboard-1-copyAsset.png" width="225" height="25"</a>
    <a href="http://localhost:3000/characters">Characters</a>
    <a href="http://localhost:3000/factions">Factions</a>
        <div class="topnav-right">
            
            
            <% if current_user %>
            <%= link_to "Your Crew", user_path(session[:user_id])%>
            <%= link_to "Log Out", logout_path %>
            <% else %>
            <%= link_to "Sign Up", signup_path %> 
            <%= link_to "Log In", login_path %>
            <% end %>
        </div>
</div>
<br>
<br>
<br>
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Username" %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

code-wars/app/views/users/edit.html.erb
<div class="navbar">
    <a href="http://localhost:3000/"><img src="http://arcos-platform.site/wp-content/uploads/2021/01/PosterArtboard-1-copyAsset.png" width="225" height="25"</a>
    <a href="http://localhost:3000/characters">Characters</a>
    <a href="http://localhost:3000/factions">Factions</a>
        <div class="topnav-right">
            
            
            <% if current_user %>
            <%= link_to "Your Crew", user_path(session[:user_id])%>
            <%= link_to "Log Out", logout_path %>
            <% else %>
            <%= link_to "Sign Up", signup_path %> 
            <%= link_to "Log In", login_path %>
            <% end %>
        </div>
</div>
<br>
<br>
<br>
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

code-wars/app/views/users/index.html.erb
<div class="navbar">
    <a href="http://localhost:3000/"><img src="http://arcos-platform.site/wp-content/uploads/2021/01/PosterArtboard-1-copyAsset.png" width="225" height="25"</a>
    <a href="http://localhost:3000/characters">Characters</a>
    <a href="http://localhost:3000/factions">Factions</a>
        <div class="topnav-right">
            
            
            <% if current_user %>
            <%= link_to "Your Crew", user_path(session[:user_id])%>
            <%= link_to "Log Out", logout_path %>
            <% else %>
            <%= link_to "Sign Up", signup_path %> 
            <%= link_to "Log In", login_path %>
            <% end %>
        </div>
</div>
<br>
<br>
<br>
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

code-wars/app/views/users/new.html.erb
<div class="navbar">
    <a href="http://localhost:3000/"><img src="http://arcos-platform.site/wp-content/uploads/2021/01/PosterArtboard-1-copyAsset.png" width="225" height="25"</a>
    <a href="http://localhost:3000/characters">Characters</a>
    <a href="http://localhost:3000/factions">Factions</a>
        <div class="topnav-right">
            
            
            <% if current_user %>
            <%= link_to "Your Crew", user_path(session[:user_id])%>
            <%= link_to "Log Out", logout_path %>
            <% else %>
            <%= link_to "Sign Up", signup_path %> 
            <%= link_to "Log In", login_path %>
            <% end %>
        </div>
</div>
<br>
<br>
<br>
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_path %>

code-wars/app/views/users/show.html.erb
<div class="navbar">
    <a href="http://localhost:3000/"><img src="http://arcos-platform.site/wp-content/uploads/2021/01/PosterArtboard-1-copyAsset.png" width="225" height="25"</a>
    <a href="http://localhost:3000/characters">Characters</a>
    <a href="http://localhost:3000/factions">Factions</a>
        <div class="topnav-right">
            
            
            <% if current_user %>
            <%= link_to "Your Crew", user_path(session[:user_id])%>
            <%= link_to "Log Out", logout_path %>
            <% else %>
            <%= link_to "Sign Up", signup_path %> 
            <%= link_to "Log In", login_path %>
            <% end %>
        </div>
</div>
<br>
<br>
<br>
<p id="notice"><%= notice %></p>

<h1> Username: <%= @user.email %> </h1>

<h2> Your characters: </h2>

<ul>
<% @user.characters.each do | character | %>
    <li> <h3> <%= link_to character.name, character_path(character.id) %> <br> </h3>
<% end %>
</ul>